name: BeTheChange
favicon: null
layout_spectrum: 0.43867042590864
typography_spectrum: 0.22870536567643285
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5587948826141655
  lightness: 0.08473846642300487
  saturation: 0.8726973200682551
  rhythmicContrast: 0.7307955038268119
purpose: []
